version: "3.8"
services:
  
  app:
    container_name: syntaxboard_djangomodels_slim
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn djangomodels.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/opt/services/djangomodels/src
    ports:
      - 8000:8000
    networks:
        - mysql_syntaxboard
networks:
  mysql_syntaxboard:
    external: true